### ISSUE TITLE
Build failed on Macos

### ISSUE THREAD

**Issue by selimanac** [otakann/Embedded-Websocket-Client-Library#2]
Is this lib compatible with MacOS, iOS or Android? I try to build it on MacOS but it fails.
Also, is it threat safe?

```
Undefined symbols for architecture x86_64:
  "_CLIB_base64_encode", referenced from:
      _WSC_Base64Encode in WSC_base64.o
  "_CLIB_htonl", referenced from:
      _WSC_htonl in WSC_net.o
  "_CLIB_htons", referenced from:
      _WSC_htons in WSC_net.o
  "_CLIB_ntohl", referenced from:
      _WSC_ntohl in WSC_net.o
  "_CLIB_ntohs", referenced from:
      _WSC_ntohs in WSC_net.o
  "_CLIB_rand", referenced from:
      _WSC_RandomGet in WSC_random.o
  "_CLIB_random_init", referenced from:
      _WSC_RandomInit in WSC_random.o
  "_CLIB_sha1_finish", referenced from:
      _WSC_ShaCal in WSC_sha.o
  "_CLIB_sha1_free", referenced from:
      _WSC_ShaCal in WSC_sha.o
  "_CLIB_sha1_init", referenced from:
      _WSC_ShaCal in WSC_sha.o
  "_CLIB_sha1_starts", referenced from:
      _WSC_ShaCal in WSC_sha.o
  "_CLIB_sha1_update", referenced from:
      _WSC_ShaCal in WSC_sha.o
  "_CLIB_srand", referenced from:
      _WSC_RandomInit in WSC_random.o
  "_CLIB_strncasecmp", referenced from:
      _WSC_CoreRead in WSC_core.o
ld: symbol(s) not found for architecture x86_64


```

**Comment by otakann** [comment]
Hi, selimanac 

Thank you very much for your comment.
I think the reason is that perhaps you did not build or link the source in "CommonLib " folder.
These functions are implemented in this folder.
Can you show the step of how your build it ?

**Comment by otakann** [comment]
Also ,There are two callback functions called "LockFunc" and "UnlockFunc" you can register in the WebSocket session handler. Implement the thread synchronization handle of your platform here will achieve the thread safe. Register NULL will not be thread safe.

**Comment by selimanac** [comment]
> I think the reason is that perhaps you did not build or link the source in "CommonLib " folder.

Hi,

You are right, I didn't link it. I just run the cmake...
I'm planning to use this in a game engine and I don't need dynamic lib anyway. I manage to build static libs with cmake -> xcode and I'm going to test it as soon as possible.

Thanks a lot

**Comment by otakann** [comment]
Hi, 
Glad that helped. If have any trouble with this library , feel free to contact me.
